### ISSUE TITLE
3020M with 4GB Ram and Intel Core I5 4570T

### ISSUE THREAD

**Issue by kniffo84** [varszegimarcell/Optiplex-3020-Hackintosh-Catalina-OpenCore#2]
Hi again,

I tried to install Catalina on a 3020M but I after changed Bios and NVRam settings next step to start installation I get follow message

![Uploading 100430915...]

**Comment by kniffo84** [comment]
Hi, sorry first post are not include the picture of the failure

**Comment by kniffo84** [comment]
![failure 3020M](https://user-images.githubusercontent.com/74502719/100432225-9271e780-3099-11eb-8823-9789f85ec6a1.jpg)

**Comment by varszegimarcell** [comment]
Hello

It seems like, the CFG Lock is not disabled, at least to my knowlege, this is why the boot stucks at this moment.

Now, to temporarly solve this issue, you should edit your conflig.plist, modify the values Kernel > Quirks > AppleCpuPmCfgLock and AppleXcpmCfgLock values. These are boolean values, set them to true. According to the OpenCore documentation, these quirks should be avoided whenever possible. For now, at least it gets you booting.

Assuming that you’ve changed the 0xDE9 NVRAM variable, and the CFG lock is still not disabled, this variable has different offset on the 3020M than the 3020SSF and the 3020MT. 

Can you do me a favor? Please follow this guide’s “Fix BIOS issues” section to make a BIOS dump, and send me the bin file please. Link to the guide: https://github.com/JimLee1996/Hackintosh_OptiPlex_9020#Fix_BIOS_Issues
BTW, you can also find the proper CFG lock variable offset for your machine if you follow this section of that guide, but I ask you to upload the bin file because it helps me to update the guide, in respect of the 3020M. I have only the 3020SSF comupter.

**Comment by kniffo84** [comment]
If I understand it right I have to do these Bin file under windows correct ?

**Comment by varszegimarcell** [comment]
> If I understand it right I have to do these Bin file under windows correct ?

Correct, sadly no tools available on Mac. It would be pretty dumb btw, as real Macs do not have an UEFI :D

**Comment by kniffo84** [comment]
I will do it for you these weekend. It´s great that you help me so much :-)

**Comment by varszegimarcell** [comment]
> I will do it for you these weekend. It´s great that you help me so much :-)

Your welcome :)

**Comment by kniffo84** [comment]
here the file
[DellInc.-A15.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-Catalina-OpenCore/files/5610633/DellInc.-A15.zip)

**Comment by kniffo84** [comment]
Please send me information or update what I have to do for changes. I try now to install Big Sur on it...

**Comment by varszegimarcell** [comment]
> Please send me information or update what I have to do for changes. I try now to install Big Sur on it...

I’ll check it out soon, thx for the dump!

**Comment by kniffo84** [comment]
It,s the dump include the changes nvram from your manual...

**Comment by varszegimarcell** [comment]
> 
> 
> It,s the dump include the changes nvram from your manual...

It really does not matter if you've modified NVRAM variables or not, I have to check just the locations of them. 

A moment pls and I'll take a look, I'll write in 5 minutes.

**Comment by varszegimarcell** [comment]
OK So it looks like the offset of the variables needed to make work the 3020M are in totally different location than they would be excepted on the 3020M.

Since we do not now what the 3020SFF and MT variables did on your machine, I would highly recommend to reset the motherboard by taking out the CMOS battery, take off the PSWD jumper, place it on the RTCST pins, connect the machine to power for 30 seconds. After that, place the jumper back on PSWD, drain all voltage remaining in the computer by pressing the power button for 30 secs. Install the CMOS battery back after. This should reset your NVRAM to default values. 

The commands needed for the 3020M are the following:

Disable CFG lock:
    
    setup_var  0x53 0x0

Set DVMT prealloc to 64MB

    setup_var 0x2F2 0x2

Enable ECHI handoff

    setup_var 0x2 0x1
    setup_var 0x187 0x1
    setup_var 0x1A4 0x2
    setup_var 0x189 0x0
    setup_var 0x18A 0x0

These should do it for the 3020M, thanks for letting me know about the issue! I'll update the guide, as well as I1ll double check the the 3020SFF and MT variables as well.

**Comment by varszegimarcell** [comment]
after doing these tweaks in your nvram, please revert your config.plist kernel quirks to the original state, as these are not needed anymore

**Comment by varszegimarcell** [comment]
Please leave me a feedback if you was able to succeed or not. :)

**Comment by kniffo84** [comment]
I will try it tomorrow 😊👍

**Comment by kniffo84** [comment]
Hi I installed direct Big Sur. The installation was ok and System works but Ethernet port is not working. If you start the system port send green and orange signals but if OC begin to boot signs get out... what is missing rest looks good 👍😊

**Comment by varszegimarcell** [comment]
> Hi I installed direct Big Sur. The installation was ok and System works but Ethernet port is not working. If you start the system port send green and orange signals but if OC begin to boot signs get out... what is missing rest looks good 👍😊

Hey, It’s nice to hear that it runs! :D 

I have no idea what’s going on with your ethernet, according to the 3020M users manual, it has Realtek RTL8151GD ethernet chipset, so it should run with the RealtekRTL8111.kext which this repository includes. Have you verified that the ethernet works on other operating systems such as windows or linux? You can try it out with a live linux usb.

**Comment by kniffo84** [comment]
I take a test with live linux usb stick and the ethernet port is working...

**Comment by kniffo84** [comment]
![image](https://user-images.githubusercontent.com/74502719/100540743-7f991780-323f-11eb-8e48-346c102ce5ee.jpeg)

Can that be a problem? I check with Kext updater

**Comment by varszegimarcell** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/74502719/100540743-7f991780-323f-11eb-8e48-346c102ce5ee.jpeg)
> 
> Can that be a problem? I check with Kext updater

I would doubt it.

I've found this on the OpenCore's kext guide:

![kép](https://user-images.githubusercontent.com/47447944/100553770-07a70d80-3290-11eb-8abb-3ff30429f934.png)

Source: https://dortania.github.io/OpenCore-Install-Guide/ktext.html#ethernet Firstly, I would try to use the older RealtekRTL8111.kext, try to revert to version 2.2.2.
 
An antoher possibility is that for some strange reason, your computer may have a different Ethernet chipset. I would try to use IntelMausi.kext instead of RealtekRTL8111.kext, I hardy can imagine any other chipset than Realtek and Intel. You can  find out the ethernet chipset's type on the live linux with the
    
    # lspci | egrep -i --color 'network|ethernet'
    
command. 

Sorry for the late respones, I work hard on my thesis at the moment.

**Comment by kniffo84** [comment]
Hi thanks for the input and that you spend so much time for that. I found the failure now. I don't know why, but my ethernet cable was the failure. I changed it and now it works 😊

Under displayport I have sound only on the front panel nothing sound is comming. I think that is the last problem all other things working 😊

**Comment by varszegimarcell** [comment]
> Hi thanks for the input and that you spend so much time for that. I found the failure now. I don't know why, but my ethernet cable was the failure. I changed it and now it works 😊
> 
> Under displayport I have sound only on the front panel nothing sound is comming. I think that is the last problem all other things working 😊

You may need to try a different audio layout, look for the layout-id value in the DeviceProperties > Add > PciRoot(0x0)/Pci(0x1b,0x0) You can find the available  audio layouts for your chipset on this link: https://github.com/acidanthera/applealc/wiki/supported-codecs

Feel free to open a new topic if you have any more issues, I’m happy that you was able to sort the problem out! :D
